"""The local payout wallet: create it, inspect it, and validate addresses.

Pearl pays mining rewards to BIP-341 taproot addresses — witness version 1,
32-byte output-key program, bech32m. The format authority is upstream's ISC
gateway (`pearl-gateway/src/pearl_gateway/blockchain_utils/blockchain_utils.py`,
`get_script_pubkey_from_p2tr_address`), which enforces exactly those three
properties and leaves the human-readable prefix free; `prl` is the prefix in
live use — LuckyPool accepted a share paying an address generated by this
code on 2026-08-10. The key→address math was differentially checked that day
against `bitcoinutils` 0.8.2, the same library the upstream gateway uses:
32 random keys, identical witness programs, plus upstream's own coinbase
fixture. Four of those runs are baked into `--self-test` stage 0.

This file is the sharpest instance of the domain's silent failure mode: a
mistyped payout address mines value nobody can claim, and a wrong tweak
produces a perfectly valid-looking address whose key cannot spend. Hence the
miner validates every address before connecting, creation re-derives and
re-decodes before writing anything, and `verify` re-checks an existing file
from the private key up.

The wallet file (`wallet.json`, mode 0600, gitignored; pre-08-10 name
`burner_wallet.json` is still honoured) is a bare keypair, not a wallet app:
it receives, and spending means importing the private key into any
taproot-capable wallet — `tr()` descriptor wallets apply the BIP-341 tweak
themselves. Why it stops there is recorded in
docs/adr/0008-included-wallet-is-a-bare-keypair.md.

Commands:

  python -m pearl_metal_miner.wallet new     create wallet.json if absent, print the address
  python -m pearl_metal_miner.wallet show    print the payout address (never the key)
  python -m pearl_metal_miner.wallet show --reveal-private-key
                                             print the private key, for import elsewhere
  python -m pearl_metal_miner.wallet verify  re-derive the address from the stored key
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import secrets
import stat
import sys

HRP = "prl"
WITNESS_VERSION = 1  # taproot; the gateway rejects everything else
PROGRAM_BYTES = 32

WALLET_BASENAME = "wallet.json"
LEGACY_BASENAME = "burner_wallet.json"

# secp256k1 (SEC 2 §2.4.1)
P = 2**256 - 2**32 - 977
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
G = (
    0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
    0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8,
)


def _inv(a, m):
    return pow(a, m - 2, m)


def _add(p1, p2):
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    (x1, y1), (x2, y2) = p1, p2
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    lam = (3 * x1 * x1 * _inv(2 * y1, P)) % P if p1 == p2 else ((y2 - y1) * _inv(x2 - x1, P)) % P
    x3 = (lam * lam - x1 - x2) % P
    return x3, (lam * (x1 - x3) - y1) % P


def _mul(k, point):
    acc = None
    while k:
        if k & 1:
            acc = _add(acc, point)
        point = _add(point, point)
        k >>= 1
    return acc


def _tagged_hash(tag: str, data: bytes) -> bytes:
    t = hashlib.sha256(tag.encode()).digest()
    return hashlib.sha256(t + t + data).digest()


# --- bech32m (BIP-350; checksum machinery shared with BIP-173) --------------

CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"
BECH32M_CONST = 0x2BC830A3


def _bech32_polymod(values):
    gen = [0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3]
    chk = 1
    for v in values:
        b = chk >> 25
        chk = (chk & 0x1FFFFFF) << 5 ^ v
        for i in range(5):
            chk ^= gen[i] if ((b >> i) & 1) else 0
    return chk


def _hrp_expand(hrp: str):
    return [ord(c) >> 5 for c in hrp] + [0] + [ord(c) & 31 for c in hrp]


def _convertbits(data, frombits, tobits, pad=True):
    """Regroup bit width; strict (pad=False) rejects non-canonical padding."""
    acc = bits = 0
    ret = []
    maxv = (1 << tobits) - 1
    for value in data:
        acc = (acc << frombits) | value
        bits += frombits
        while bits >= tobits:
            bits -= tobits
            ret.append((acc >> bits) & maxv)
    if pad:
        if bits:
            ret.append((acc << (tobits - bits)) & maxv)
    elif bits >= frombits or ((acc << (tobits - bits)) & maxv):
        return None
    return ret


def encode_address(program: bytes, hrp: str = HRP, witver: int = WITNESS_VERSION) -> str:
    data = [witver] + _convertbits(program, 8, 5)
    polymod = _bech32_polymod(_hrp_expand(hrp) + data + [0] * 6) ^ BECH32M_CONST
    checksum = [(polymod >> 5 * (5 - i)) & 31 for i in range(6)]
    return hrp + "1" + "".join(CHARSET[d] for d in data + checksum)


def decode_payout_address(addr: str) -> bytes:
    """Return the 32-byte witness program, or raise ValueError saying — in
    plain language — what is wrong. Mirrors the checks upstream's gateway
    applies when it builds the coinbase paying this address, so anything
    accepted here is an address the chain can actually pay."""
    addr = addr.strip()
    if not addr:
        raise ValueError("the address is empty")
    if addr != addr.lower() and addr != addr.upper():
        raise ValueError("mixed upper/lower case — a valid address is all one case")
    addr = addr.lower()
    if len(addr) > 90:
        raise ValueError("too long to be a valid address")
    sep = addr.rfind("1")
    if sep < 1 or sep + 7 > len(addr):
        raise ValueError("not a bech32m address (missing the '1' separator)")
    hrp, data_part = addr[:sep], addr[sep + 1:]
    if any(c not in CHARSET for c in data_part):
        bad = next(c for c in data_part if c not in CHARSET)
        raise ValueError(f"invalid character {bad!r} — probably a typo "
                         "(note: '1', 'b', 'i', 'o' never appear after the separator)")
    data = [CHARSET.index(c) for c in data_part]
    const = _bech32_polymod(_hrp_expand(hrp) + data)
    if const == 1:
        raise ValueError("valid bech32, but Pearl taproot addresses use bech32m — "
                         "this looks like an address of a different type")
    if const != BECH32M_CONST:
        raise ValueError("checksum mismatch — the address has a typo somewhere")
    if hrp != HRP:
        hint = " (that prefix belongs to Bitcoin)" if hrp in ("bc", "tb") else ""
        raise ValueError(f"prefix {hrp!r} is not a Pearl address{hint} — "
                         f"a Pearl address starts with '{HRP}1'")
    witver, program5 = data[0], data[1:-6]
    if witver != WITNESS_VERSION:
        raise ValueError(f"witness version {witver}, but Pearl pays taproot "
                         f"(version {WITNESS_VERSION}) addresses — they start with '{HRP}1p'")
    program8 = _convertbits(program5, 5, 8, pad=False)
    if program8 is None or len(program8) != PROGRAM_BYTES:
        raise ValueError("the address decodes to the wrong length — "
                         "it is truncated or has extra characters")
    return bytes(program8)


def validate_payout_address(addr: str) -> str:
    """Validate and return the normalised (lowercase) address."""
    decode_payout_address(addr)
    return addr.strip().lower()


# --- key → address (BIP-340 even-Y key, BIP-341 key-path tweak) -------------

def derive_address(priv: int) -> tuple[int, str]:
    """Return (normalised private key, address). The normalised key is the
    even-Y representative (BIP-340), so re-deriving from the stored key is
    deterministic. Raises ValueError for the ~2^-128 out-of-range tweak —
    callers generating fresh keys just draw again."""
    if not 1 <= priv < N:
        raise ValueError("private key out of range")
    px, py = _mul(priv, G)
    if py % 2 != 0:
        priv = N - priv
        px, py = _mul(priv, G)
    internal = px.to_bytes(32, "big")
    tweak = int.from_bytes(_tagged_hash("TapTweak", internal), "big")
    if tweak >= N:
        raise ValueError("tweak out of range (astronomically unlikely)")
    out_x, _ = _add((px, py), _mul(tweak, G))
    return priv, encode_address(out_x.to_bytes(32, "big"))


# --- the wallet file --------------------------------------------------------

def _repo_root() -> str:
    return os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))


def default_wallet_path() -> str:
    return os.path.join(_repo_root(), WALLET_BASENAME)


def find_wallet_file() -> str | None:
    """The canonical file, else the pre-08-10 legacy name, else None."""
    for base in (WALLET_BASENAME, LEGACY_BASENAME):
        path = os.path.join(_repo_root(), base)
        if os.path.exists(path):
            return path
    return None


def load_wallet(path: str) -> dict:
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        raise ValueError(f"cannot read wallet file {path}: {e}") from e
    if "address" not in data:
        raise ValueError(f"wallet file {path} has no 'address' field")
    return data


def create_wallet(path: str) -> dict:
    """Generate a fresh keypair and write it to `path` (mode 0600). Refuses
    to overwrite: an existing file may already own mined funds."""
    while True:
        try:
            priv, address = derive_address(secrets.randbelow(N - 1) + 1)
            break
        except ValueError:
            continue  # out-of-range tweak: draw a fresh key
    # Re-check the finished article before writing: the address must decode
    # back to a program, and the stored key must re-derive the same address.
    program = decode_payout_address(address)
    assert len(program) == PROGRAM_BYTES
    assert derive_address(priv)[1] == address
    data = {
        "address": address,
        "private_key_hex": f"{priv:064x}",
        "internal_key_x_hex": _mul(priv, G)[0].to_bytes(32, "big").hex(),
        "created_utc": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "note": "Payout wallet created by pearl-metal-miner. The private key is "
                "the only claim on anything mined to this address: keep this file "
                "secret and back it up. To spend, import the private key into a "
                "taproot-capable wallet (tr() descriptor wallets apply the "
                "BIP-341 tweak themselves).",
    }
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    return data


def payout_address_from_disk() -> tuple[str, str] | None:
    """(validated address, path) from the wallet file, or None if there is no
    wallet. A file that exists but does not validate raises — mining to a
    corrupt wallet must be loud, not silent."""
    path = find_wallet_file()
    if path is None:
        return None
    data = load_wallet(path)
    try:
        address = validate_payout_address(data["address"])
    except ValueError as e:
        raise ValueError(f"the address in {path} is invalid ({e}) — "
                         "run: python -m pearl_metal_miner.wallet verify") from e
    return address, path


def verify_wallet(path: str) -> list[tuple[str, bool, str]]:
    """Re-check a wallet file from the private key up. Returns (name, ok,
    detail) per check; any False means do not mine to this file."""
    checks: list[tuple[str, bool, str]] = []
    try:
        data = load_wallet(path)
    except ValueError as e:
        return [("wallet file loads", False, str(e))]
    checks.append(("wallet file loads", True, path))

    addr = str(data.get("address", ""))
    try:
        validate_payout_address(addr)
        checks.append(("address well-formed (bech32m, taproot, 32-byte program)", True, addr))
    except ValueError as e:
        checks.append(("address well-formed (bech32m, taproot, 32-byte program)", False, str(e)))

    key_hex = data.get("private_key_hex")
    if key_hex is None:
        checks.append(("private key present", False,
                       "no 'private_key_hex' — the file can receive but never spend"))
        return checks
    try:
        priv = int(key_hex, 16)
        norm, derived = derive_address(priv)
        checks.append(("private key parses and is in range", True, ""))
        checks.append(("private key re-derives the stored address", derived == addr.lower(),
                       "" if derived == addr.lower() else f"key derives {derived}"))
        stored_internal = data.get("internal_key_x_hex")
        if stored_internal is not None:
            internal = _mul(norm, G)[0].to_bytes(32, "big").hex()
            checks.append(("internal key consistent with private key", internal == stored_internal,
                           "" if internal == stored_internal else "internal_key_x_hex mismatch"))
    except (ValueError, TypeError) as e:
        checks.append(("private key parses and is in range", False, str(e)))
    return checks


# --- CLI --------------------------------------------------------------------

def _cmd_new(path: str | None) -> int:
    if path is None:
        existing = find_wallet_file()
        if existing is not None:
            data = load_wallet(existing)
            print(f"a wallet already exists at {existing} — keeping it "
                  "(delete or move the file first if you truly want a fresh one)",
                  file=sys.stderr)
            print(data["address"])
            return 0
        path = default_wallet_path()
    elif os.path.exists(path):
        print(f"a wallet already exists at {path} — keeping it "
              "(delete or move the file first if you truly want a fresh one)",
              file=sys.stderr)
        print(load_wallet(path)["address"])
        return 0
    data = create_wallet(path)
    print(f"""created {path}  (file mode 0600, gitignored)

  your payout address: {data['address']}

Three things to understand about this file:
  - The file IS the money. Anything mined to that address is claimable only
    with the private key inside it. Back the file up; if the only copy is
    lost, so are the funds.
  - It receives; it does not spend. To spend, import the private key
    (…wallet show --reveal-private-key) into any taproot-capable wallet.
  - The miner uses this address automatically whenever --address is omitted.
""", file=sys.stderr)
    print(data["address"])
    return 0


def _resolve(path: str | None) -> str | None:
    if path is not None:
        return path if os.path.exists(path) else None
    return find_wallet_file()


def _cmd_show(path: str | None, reveal: bool) -> int:
    found = _resolve(path)
    if found is None:
        print("no wallet file found — create one with: "
              "python -m pearl_metal_miner.wallet new", file=sys.stderr)
        return 1
    data = load_wallet(found)
    if reveal:
        if "private_key_hex" not in data:
            print(f"{found} holds no private key", file=sys.stderr)
            return 1
        print("this key is the money — anyone who sees it can take anything "
              "mined to the address", file=sys.stderr)
        print(data["private_key_hex"])
    else:
        print(data["address"])
    return 0


def _cmd_verify(path: str | None) -> int:
    found = _resolve(path)
    if found is None:
        print("no wallet file found — create one with: "
              "python -m pearl_metal_miner.wallet new", file=sys.stderr)
        return 1
    checks = verify_wallet(found)
    failed = 0
    for name, ok, detail in checks:
        print(f"  [{'ok ' if ok else 'FAIL'}] {name}" + (f" — {detail}" if detail else ""))
        failed += 0 if ok else 1
    mode = stat.S_IMODE(os.stat(found).st_mode)
    if mode & 0o077:
        print(f"  note: file mode is {mode:03o}; consider `chmod 600 {found}`")
    if failed:
        print(f"WALLET VERIFY FAIL — {failed} of {len(checks)} checks failed. "
              "Do not mine to this file.")
        return 1
    print(f"WALLET VERIFY PASS — {len(checks)} checks.")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m pearl_metal_miner.wallet",
        description="Create and inspect the local payout wallet "
                    "(a bare keypair file — see the module docstring).")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_new = sub.add_parser("new", help="create wallet.json if absent; print the address")
    p_show = sub.add_parser("show", help="print the payout address")
    p_show.add_argument("--reveal-private-key", action="store_true",
                        help="print the private key instead (for import into a real wallet)")
    p_verify = sub.add_parser("verify", help="re-derive the address from the stored key")
    for p in (p_new, p_show, p_verify):
        p.add_argument("--path", help=f"wallet file (default: ./{WALLET_BASENAME}, "
                                      f"honouring legacy ./{LEGACY_BASENAME})")
    args = ap.parse_args(argv)
    try:
        if args.cmd == "new":
            return _cmd_new(args.path)
        if args.cmd == "show":
            return _cmd_show(args.path, args.reveal_private_key)
        return _cmd_verify(args.path)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
