#!/bin/sh
# Build libpearlmetal.dylib with the Command Line Tools alone.
# No Xcode, no `xcrun metal`, no .metallib step: shader source is embedded and
# compiled at process start (ADR-0004).
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/csrc/metal"
OUT="$ROOT/build"
mkdir -p "$OUT"

# Embed the MSL source as a byte array (any content-safe, no quoting games).
python3 - "$SRC/kernels/pearl_kernels.metal" "$SRC/kernels_embedded.h" <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w") as f:
    f.write("/* Generated by packaging/build_macos.sh — do not edit. */\n")
    f.write("static const unsigned char PEARL_KERNELS_MSL[] = {")
    f.write(",".join(str(b) for b in data))
    f.write("};\n")
    f.write(f"static const unsigned long PEARL_KERNELS_MSL_LEN = {len(data)};\n")
PY

clang++ -std=c++17 -O2 -fobjc-arc -dynamiclib \
  -framework Metal -framework Foundation \
  -o "$OUT/libpearlmetal.dylib" \
  "$SRC/pearl_metal.mm"

echo "built $OUT/libpearlmetal.dylib"
