"""Generate a claimable burner address for pipeline testing.

Pearl addresses are BIP-341 taproot (witness v1, bech32m, HRP "prl") — the
upstream gateway builds coinbases with the `bitcoinutils` BTC library. This
produces a random secp256k1 key, applies the BIP-341 key-path tweak with an
empty script tree, and encodes the output key. The private key is written to
burner_wallet.json (gitignored) so anything mined is claimable, not burned.

This is a TESTING wallet: replace with your own wallet's address for real
mining, and treat the JSON as a secret.
"""

import hashlib
import json
import os
import secrets

P = 2**256 - 2**32 - 977
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
G = (
    0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
    0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8,
)


def _inv(a, m):
    return pow(a, m - 2, m)


def _add(p1, p2):
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    (x1, y1), (x2, y2) = p1, p2
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    lam = (3 * x1 * x1 * _inv(2 * y1, P)) % P if p1 == p2 else ((y2 - y1) * _inv(x2 - x1, P)) % P
    x3 = (lam * lam - x1 - x2) % P
    return x3, (lam * (x1 - x3) - y1) % P


def _mul(k, point):
    acc = None
    while k:
        if k & 1:
            acc = _add(acc, point)
        point = _add(point, point)
        k >>= 1
    return acc


def _tagged_hash(tag, data):
    t = hashlib.sha256(tag.encode()).digest()
    return hashlib.sha256(t + t + data).digest()


def _lift_x(x):
    y_sq = (pow(x, 3, P) + 7) % P
    y = pow(y_sq, (P + 1) // 4, P)
    if y * y % P != y_sq:
        raise ValueError("x not on curve")
    return (x, y if y % 2 == 0 else P - y)


CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"


def _bech32_polymod(values):
    gen = [0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3]
    chk = 1
    for v in values:
        b = chk >> 25
        chk = (chk & 0x1FFFFFF) << 5 ^ v
        for i in range(5):
            chk ^= gen[i] if ((b >> i) & 1) else 0
    return chk


def _bech32m_encode(hrp, witver, prog):
    data = [witver] + _convertbits(prog, 8, 5)
    hrp_exp = [ord(c) >> 5 for c in hrp] + [0] + [ord(c) & 31 for c in hrp]
    polymod = _bech32_polymod(hrp_exp + data + [0] * 6) ^ 0x2BC830A3
    checksum = [(polymod >> 5 * (5 - i)) & 31 for i in range(6)]
    return hrp + "1" + "".join(CHARSET[d] for d in data + checksum)


def _convertbits(data, frombits, tobits):
    acc = bits = 0
    ret = []
    maxv = (1 << tobits) - 1
    for value in data:
        acc = (acc << frombits) | value
        bits += frombits
        while bits >= tobits:
            bits -= tobits
            ret.append((acc >> bits) & maxv)
    if bits:
        ret.append((acc << (tobits - bits)) & maxv)
    return ret


def main():
    out = os.path.join(os.path.dirname(__file__), "..", "burner_wallet.json")
    if os.path.exists(out):
        with open(out) as f:
            print(json.load(f)["address"])
        return
    priv = secrets.randbelow(N - 1) + 1
    px, py = _mul(priv, G)
    if py % 2 != 0:  # BIP-340: use the even-Y key, negate the secret
        priv = N - priv
        px, py = _mul(priv, G)
    internal = px.to_bytes(32, "big")
    tweak = int.from_bytes(_tagged_hash("TapTweak", internal), "big")
    if tweak >= N:
        raise SystemExit("tweak out of range (astronomically unlikely) — rerun")
    out_x, out_y = _add((px, py), _mul(tweak, G))
    address = _bech32m_encode("prl", 1, out_x.to_bytes(32, "big"))
    with open(out, "w") as f:
        json.dump({
            "address": address,
            "private_key_hex": f"{priv:064x}",
            "internal_key_x_hex": internal.hex(),
            "tweaked_priv_would_be": "priv + H_tapTweak(internal) mod n (BIP-341 key path)",
            "note": "TESTING wallet generated by tools/make_burner_wallet.py. "
                    "Import into a taproot-capable wallet to claim. Keep secret.",
        }, f, indent=2)
    os.chmod(out, 0o600)
    print(address)


if __name__ == "__main__":
    main()
